### ISSUE TITLE
Add JavaScript code examples

### ISSUE THREAD

**Issue by Zubs** [redislabs-training/ru101#12]

**Comment by simonprickett** [comment]
Hi there - thanks for the feedback.

This is not something we'll add to this course.  We provide JavaScript examples in our RU102JS and RU204 courses, and they'll also be in the upcoming RU205 course.  The 101 course is designed to be independent of programming language, and when we have to use a bit of code in a course like this we use Python as it's easiest for people from all backgrounds to follow.  We take this approach in the RU202 course too.

Cheers,

Simon.
